Bootstrap: docker
From: ubuntu:20.04

%environment
    export PATH=/usr/local/bin:$PATH

%post
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        wget \
        curl \
        gnupg \
        apt-transport-https \
        ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

    # Install BaseMount
    echo "# Packages by Illumina BaseSpace" | tee /etc/apt/sources.list.d/basemount.list
    echo "deb [arch=amd64 trusted=yes] https://basemount-prod.s3.amazonaws.com/ ubuntu main" | tee -a /etc/apt/sources.list.d/basemount.list
    apt-get update || echo "Warning: apt-get update had a few warnings"
    apt-get install -y basemount
    apt-get clean && rm -rf /var/lib/apt/lists/*

%labels
    Author David Olmo Marchal
    Version v1.0
    Description "Singularity container with Illumina BaseMount"
