Bootstrap: docker
From: ubuntu:20.04

%environment
    export PATH=/opt/jax-cnv/bin:/opt/jellyfish/bin:$PATH

%post
    set -e  # stop on first error

	apt-get update
	DEBIAN_FRONTEND=noninteractive apt-get install -y \
	    build-essential \
	    gcc \
	    g++ \
	    zlib1g-dev \
	    wget \
	    git \
	    make \
	    automake \
	    autoconf \
	    libtool \
	    pkg-config \
	    bzip2 \
	    libssl-dev \
	    libbz2-dev \
	    liblzma-dev \
	    libcurl4-openssl-dev \
	    python3 \
	    python3-pip \
	    cmake \
	    curl \
	    ca-certificates \
	    libncurses5-dev \
	    libncursesw5-dev

    apt-get clean
    rm -rf /var/lib/apt/lists/*

    # Install Samtools
    cd /opt
    wget https://github.com/samtools/samtools/releases/download/1.22/samtools-1.22.tar.bz2
    tar -xvjf samtools-1.22.tar.bz2
    cd samtools-1.22
    ./configure --prefix=/usr/local
    make
    make install

    # Clone JAX-CNV and update submodules
    mkdir -p /tools
    cd /tools
    git clone https://github.com/TheJacksonLaboratory/JAX-CNV.git
    cd JAX-CNV
    git submodule init
    git config submodule.lib/fastaq.url https://github.com/wanpinglee/fastaq.git
    git submodule update --recursive --init

    # Build JAX-CNV
    cd /tools/JAX-CNV
    make || (echo "Build failed" && exit 1)

    # Install Jellyfish
    mkdir -p /opt/jellyfish && cd /opt/jellyfish
    wget https://github.com/gmarcais/Jellyfish/releases/download/v2.3.0/jellyfish-2.3.0.tar.gz
    tar -xvzf jellyfish-2.3.0.tar.gz
    cd jellyfish-2.3.0
    ./configure --prefix=/opt/jellyfish
    make
    make install


%labels
    Author David Olmo Marchal - Mario Ruiz Pérez
    Version v1.0
    Description "Singularity container with JAX-CNV + Jellyfish"
