Bootstrap: docker
From: ubuntu:20.04

%environment
    export PATH=/opt/jax-cnv/bin:/opt/jellyfish/bin:$PATH

%post
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential \
        gcc \
        g++ \
        zlib1g-dev \
        wget \
        git \
        make \
        automake \
        samtools \
        autoconf \
        libtool \
        pkg-config \
        bzip2 \
        libbz2-dev \
        liblzma-dev \
        python3 \
        python3-pip \
        cmake && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

    # Install JAX-CNV
    mkdir -p /opt/jax-cnv && cd /opt/jax-cnv
    git clone https://github.com/TheJacksonLaboratory/jax-cnv.git .
    make

    # Install Jellyfish
    mkdir -p /opt/jellyfish && cd /opt/jellyfish
    wget https://github.com/gmarcais/Jellyfish/releases/download/v2.3.0/jellyfish-2.3.0.tar.gz
    tar -xvzf jellyfish-2.3.0.tar.gz
    cd jellyfish-2.3.0
    ./configure --prefix=/opt/jellyfish
    make && make install

%labels
    Author David Olmo Marchal
    Version v1.0
    Description "Singularity container with JAX-CNV + Jellyfish"
